<div class="main-content">
    <div class="login-box">
        <div class="login-window">
            <form action="./login.php" method="post">
                <div class="login-title">Login</div>
                <div class="mui-textfield mui-textfield--float-label">
                    <label>Email: </label>
                    <input type="email" name="email" id="email" required>
                </div>
                <div class="mui-textfield mui-textfield--float-label">
                    <label>Senha: </label>
                    <input type="password" name="senha" id="senha" required>
                </div>
                <input type="submit" value="Enviar" class="mui-btn">
            </form>
            <div>
                <a class="mui-btn" href="cadastro.php">Cadastre-se</a>
            </div>
        </div>
    </div>
</div>